- name: Setup silverbullet host
  hosts: silverbullet_hosts
  become: true
  vars:
    user_name: chiyonn
    nfs_server: 192.168.40.3
    nfs_silverbullet_path: /volume1/silverbullet
    nfs_shared_path: /volume1/shared
  tasks:

    - name: Install neovim
      apt:
        name: neovim
        state: present

    - import_tasks: common/mount-shared.yaml

    - import_tasks: common/setup-github.yaml

    - name: Create ~/.config directory for user chiyonn
      file:
        path: "/home/{{ user_name }}/.config"
        state: directory
        mode: '0700'
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Git clone nvim repository
      git:
        repo: git@github.com:chiyonn/nvim.git
        dest: "/home/{{ user_name }}/.config/nvim"
        key_file: "/home/{{ user_name }}/.ssh/github"
        accept_hostkey: yes
        version: main
      become: false
      vars:
        ansible_ssh_private_key_file: "/home/{{ user_name }}/.ssh/github"
