- name: Setup fappom host
  hosts: fappom_hosts
  become: true
  vars:
    user_name: chiyonn
    nfs_server: 192.168.40.3
    nfs_fappom_path: /volume1/fappom
    nfs_shared_path: /volume1/shared
  tasks:

    - name: Install nfs-common package
      apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: Create mount directory
      file:
        path: /mnt/fappom
        state: directory
        mode: '0755'

    - name: Mount NFS share(fappom)
      mount:
        path: /mnt/fappom
        src: "{{ nfs_server }}:{{ nfs_fappom_path }}"
        fstype: nfs
        opts: defaults
        state: mounted

    - name: Create /mnt/shared directory
      file:
        path: /mnt/shared
        state: directory
        mode: '0755'

    - name: Mount NFS share(shared)
      mount:
        path: /mnt/shared
        src: "{{ nfs_server }}:{{ nfs_shared_path }}"
        fstype: nfs
        opts: defaults
        state: mounted

    - name: Create ~/.ssh directory for user chiyonn
      file:
        path: "/home/{{ user_name }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Symlink GitHub key
      file:
        src: /mnt/shared/secrets/keys/github
        dest: "/home/{{ user_name }}/.ssh/github"
        state: link
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Git clone fappom repository
      git:
        repo: git@github.com:chiyonn/fappom.git
        dest: "/home/{{ user_name }}/fappom"
        key_file: "/home/{{ user_name }}/.ssh/github"
        accept_hostkey: yes
        version: main
      become: false
      vars:
        ansible_ssh_private_key_file: "/home/{{ user_name }}/.ssh/github"

    - name: Symlink env file
      file:
        src: /mnt/shared/secrets/envs/fappom.dev.env
        dest: "/home/{{ user_name }}/fappom/.env"
        state: link
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
