- name: Setup fappom host
  hosts: fappom_hosts
  become: true
  vars:
    user_name: chiyonn
    nfs_server: 192.168.40.3
    nfs_fappom_path: /volume1/fappom
    nfs_shared_path: /volume1/shared
  roles:
    - common
    - docker
    - fappom
