- name: Setup silverbullet host
  hosts: silverbullet_hosts
  become: true
  vars:
    user_name: chiyonn
    nfs_server: 192.168.40.3
    nfs_silverbullet_path: /volume1/silverbullet
    nfs_shared_path: /volume1/shared
  tasks:

    - name: Install nfs-common package
      apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: Create mount directory
      file:
        path: /mnt/silverbullet
        state: directory
        mode: '0755'

    - name: Mount NFS share(silverbullet)
      mount:
        path: /mnt/silverbullet
        src: "{{ nfs_server }}:{{ nfs_silverbullet_path }}"
        fstype: nfs
        opts: defaults
        state: mounted

    - import_tasks: common/mount-shared.yaml

    - import_tasks: common/setup-github.yaml

    - name: Git clone silverbullet repository
      git:
        repo: git@github.com:chiyonn/silverbullet.git
        dest: "/home/{{ user_name }}/silverbullet"
        key_file: "/home/{{ user_name }}/.ssh/github"
        accept_hostkey: yes
        version: main
      become: false
      vars:
        ansible_ssh_private_key_file: "/home/{{ user_name }}/.ssh/github"

    - name: Symlink env file
      file:
        src: /mnt/shared/secrets/envs/silverbullet.prd.env
        dest: "/home/{{ user_name }}/silverbullet/.env"
        state: link
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
